spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db
    enabled: true
    schemas: public
    username: "postgres"
    password: "123456"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30

jwt:
  signing:
    key: SpringBootTrainingsdfhsdfgsr4gsfgsregsfgsfdg#$%S%G

